name: usqnet
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipykernel
  - ipython
  - jupyter
  - pillow
  - setuptools
  - wheel
  - freetype
  - tk
  - zeromq
  - zlib
  - sqlite
  - openssl
  - readline

  - pip:
    - absl-py==1.0.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - astunparse==1.6.3
    - black==21.4b2
    - cachetools==5.0.0
    - catkin-pkg==0.4.24
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cloudpickle==2.1.0
    - cycler==0.11.0
    - distro==1.7.0
    - docutils==0.18.1
    - dtw==1.4.0
    - flatbuffers==1.12
    - fonttools==4.30.0
    - future==0.18.2
    - fvcore==0.1.5.post20220512
    - gast==0.4.0
    - gnupg==2.3.1
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grad-cam==1.3.9
    - grpcio==1.44.0
    - h5py==3.7.0
    - htmlmin==0.1.12
    - hydra-core==1.1.2
    - idna==3.3
    - imagehash==4.2.1
    - imageio==2.16.1
    - importlib-resources==5.2.3
    - imutils==0.5.4
    - iopath==0.1.9
    - ipdb==0.13.9
    - joblib==1.0.1
    - kaggle==1.5.12
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==14.0.1
    - lightgbm==3.3.2
    - lxml==4.8.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mediapipe==0.8.9.1
    - missingno==0.5.1
    - mouseinfo==0.1.3
    - multimethod==1.7
    - mypy-extensions==0.4.3
    - networkx==2.7.1
    - numpy==1.22.3
    - numpy-quaternion==2022.4.1
    - oauthlib==3.2.0
    - omegaconf==2.1.2
    - opencv-contrib-python==4.5.5.64
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - pandas==1.4.1
    - pandas-profiling==3.1.0
    - pathspec==0.9.0
    - phik==0.12.1
    - pillow==9.0.1
    - portalocker==2.4.0
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyautogui==0.9.53
    - pycocotools==2.0.4
    - pycryptodomex==3.14.1
    - pydantic==1.9.0
    - pydot==1.4.2
    - pygetwindow==0.0.9
    - pymsgbox==1.0.9
    - pyperclip==1.8.2
    - pyqt5==5.14.1
    - pyqt5-sip==12.10.1
    - pyquaternion==0.9.9
    - pyrect==0.2.0
    - pyscreeze==0.1.28
    - python-slugify==6.1.2
    - python3-xlib==0.15
    - pytweening==1.0.4
    - pytz==2021.3
    - pywavelets==1.3.0
    - pyyaml==6.0
    - regex==2022.4.24
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rospkg==1.4.0
    - rsa==4.8
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - simpleitk==2.1.1.2
    - tabulate==0.8.9
    - tangled-up-in-unicode==0.1.0
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - threadpoolctl==3.1.0
    - tifffile==2022.3.16
    - toml==0.10.2
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.63.0
    - ttach==0.0.3
    - urllib3==1.26.8
    - visions==0.7.4
    - werkzeug==2.1.1
    - wrapt==1.14.1
    - yacs==0.1.8
